# Generated by Django 4.2.2 on 2023-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('L', 'Litres')], max_length=50, null=True),
        ),
    ]
