# Generated by Django 4.2.2 on 2023-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_remove_groceryitem_group_groceryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('FR-VG', 'Fruits & Vegetables'), ('DAI-EG', 'Dairy & Eggs'), ('CHS', 'Cheese'), ('BAK', 'Bakery'), ('DR', 'Drinks'), ('FRZ', 'Frozen food'), ('SN-CAN', 'Snacks & Candies'), ('MT-SF', 'Meat & Seafood'), ('CLS', 'Cleaning Supplies'), ('PERS', 'Personal Care'), ('HLTH', 'Health'), ('MISC', 'Miscellaneous')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
