# Generated by Django 4.2.2 on 2023-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_groceryitem_category_alter_groceryitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
